# ***📥 Notebook 1 — Data Collection & EDA***
**Project:** Food Delivery Time Prediction


### What this notebook does:
- Loads the dataset from `data\raw\Food_Delivery_Time_Prediction.csv`
- Inspects shape, columns, null values
- Selects relevant columns
- Fixes missing values
- Parses dates & engineers new features
- Encoding
- Scaling / normalization
- Saves cleaned data → `data\processed\processed_data.csv`

---

# **Paths**

In [41]:
# Paths for data collection and storage 

RAW_DATA_PATH = '../data/raw/Food_Delivery_Time_Prediction.csv'
OUTPUT_DIR    = '../data/processed/processed_data.csv'

# **Libraries**

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ***Step 1 - Data Import and Preprocessing***

# **Loading Dataset**

In [43]:
print("📂 Loading balanced dataset...")
df = pd.read_csv(RAW_DATA_PATH, low_memory=False)
print(f'✅ Dataset loaded!')

📂 Loading balanced dataset...
✅ Dataset loaded!

# **Checking Missing values**

In [44]:
print('Checking null values....')

if df.isnull().values.any():
    print('Null values in the data need to be handled')
else:
    print('There are no null values in the data')

Checking null values....
There are no null values in the data

____

# **Checking Duplicate Values**

In [45]:
print('Checking Duplicate values....')

if df.duplicated().any():
    print('Duplicate values are there take necessary actions')
else:
    print('No duplicate values in the data')

Checking Duplicate values....
No duplicate values in the data

____

# **Data Info**

In [46]:
print(f'There are {df.shape[1]} columns and {df.shape[0]} rows in the dataset')

There are 15 columns and 200 rows in the dataset

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order_ID                    200 non-null    str
 1   Customer_Location           200 non-null    str
 2   Restaurant_Location         200 non-null    str
 3   Distance                    200 non-null    float64
 4   Weather_Conditions          200 non-null    str
 5   Traffic_Conditions          200 non-null    str
 6   Delivery_Person_Experience  200 non-null    int64
 7   Order_Priority              200 non-null    str
 8   Order_Time                  200 non-null    str
 9   Vehicle_Type                200 non-null    str
 10  Restaurant_Rating           200 non-null    float64
 11  Customer_Rating             200 non-null    float64
 12  Delivery_Time               200 non-null    float64
 13  Order_Cost                  200 non-null    float64
 14  Tip_Amount                  200 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 23.6 KB

In [48]:
df.describe()

,Distance,Delivery_Person_Experience,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,11.498050,5.250000,3.738500,3.686500,70.494950,1046.488700,46.616650
std,6.841755,2.745027,0.703021,0.697063,29.830694,548.568922,29.361706
min,0.520000,1.000000,2.500000,2.600000,15.230000,122.300000,1.240000
25%,6.090000,3.000000,3.200000,3.100000,46.997500,553.270000,21.602500
50%,10.265000,5.000000,3.800000,3.700000,72.775000,1035.950000,47.530000
75%,16.497500,8.000000,4.300000,4.300000,96.650000,1543.125000,70.245000
max,24.900000,10.000000,5.000000,5.000000,119.670000,1997.420000,99.740000

_______

In [49]:
df.head(5)

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
0,ORD0001,"(17.030479, 79.743077)","(12.358515, 85.100083)",1.57,Rainy,Medium,4,Medium,Afternoon,Car,4.1,3.0,26.22,1321.10,81.54
1,ORD0002,"(15.398319, 86.639122)","(14.174874, 77.025606)",21.32,Cloudy,Medium,8,Low,Night,Car,4.5,4.2,62.61,152.21,29.02
2,ORD0003,"(15.687342, 83.888808)","(19.594748, 82.048482)",6.95,Snowy,Medium,9,High,Night,Bike,3.3,3.4,48.43,1644.38,64.17
3,ORD0004,"(20.415599, 78.046984)","(16.915906, 78.278698)",13.79,Cloudy,Low,2,Medium,Evening,Bike,3.2,3.7,111.63,541.25,79.23
4,ORD0005,"(14.786904, 78.706532)","(15.206038, 86.203182)",6.72,Rainy,High,6,Low,Night,Bike,3.5,2.8,32.38,619.81,2.34

In [50]:
df['Order_Time']

0      Afternoon
1          Night
2          Night
3        Evening
4          Night
         ...
195        Night
196        Night
197    Afternoon
198        Night
199      Morning
Name: Order_Time, Length: 200, dtype: str

# **Data Transformation**

# *Encoding*

In [51]:
print(f'Unique Values in Weather_Conditions:\n{df['Weather_Conditions'].values.unique()}\n\n')
print(f'Unique Values in Traffic_Conditions:\n{df['Traffic_Conditions'].values.unique()}\n\n')
print(f'Unique Values in Order_Priority:\n{df['Order_Priority'].values.unique()}\n\n')
print(f'Unique Values in Order_Time:\n{df['Order_Time'].values.unique()}\n\n')
print(f'Unique Values in Vehicle_Type:\n{df['Vehicle_Type'].values.unique()}')


unique_df = pd.DataFrame({
    col: pd.Series(df[col].unique())
    for col in ["Weather_Conditions", "Traffic_Conditions", "Order_Priority", "Order_Time", "Vehicle_Type"]
})
unique_df

Unique Values in Weather_Conditions:
<StringArray>
['Rainy', 'Cloudy', 'Snowy', 'Sunny']
Length: 4, dtype: str


Unique Values in Traffic_Conditions:
<StringArray>
['Medium', 'Low', 'High']
Length: 3, dtype: str


Unique Values in Order_Priority:
<StringArray>
['Medium', 'Low', 'High']
Length: 3, dtype: str


Unique Values in Order_Time:
<StringArray>
['Afternoon', 'Night', 'Evening', 'Morning']
Length: 4, dtype: str


Unique Values in Vehicle_Type:
<StringArray>
['Car', 'Bike', 'Bicycle']
Length: 3, dtype: str

  Weather_Conditions Traffic_Conditions Order_Priority Order_Time Vehicle_Type
0              Rainy             Medium         Medium  Afternoon          Car
1             Cloudy                Low            Low      Night         Bike
2              Snowy               High           High    Evening      Bicycle
3              Sunny                NaN            NaN    Morning          NaN

*As from the above data frame we can see that:*
*Weather_Conditions, Order_Time and Vehicle_Type so we will use one hot encoder*
*Where as Traffic_Conditions and Order_Priority has an order, so instead of label encoder we will use manual mapping*

In [52]:
# Freture creatin rush hour

df['Rush_Hour'] = df['Order_Time'].apply(lambda x: 1 if x in ['Evening', 'Night'] else 0)

In [53]:
df.head()

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount,Rush_Hour
0,ORD0001,"(17.030479, 79.743077)","(12.358515, 85.100083)",1.57,Rainy,Medium,4,Medium,Afternoon,Car,4.1,3.0,26.22,1321.10,81.54,0
1,ORD0002,"(15.398319, 86.639122)","(14.174874, 77.025606)",21.32,Cloudy,Medium,8,Low,Night,Car,4.5,4.2,62.61,152.21,29.02,1
2,ORD0003,"(15.687342, 83.888808)","(19.594748, 82.048482)",6.95,Snowy,Medium,9,High,Night,Bike,3.3,3.4,48.43,1644.38,64.17,1
3,ORD0004,"(20.415599, 78.046984)","(16.915906, 78.278698)",13.79,Cloudy,Low,2,Medium,Evening,Bike,3.2,3.7,111.63,541.25,79.23,1
4,ORD0005,"(14.786904, 78.706532)","(15.206038, 86.203182)",6.72,Rainy,High,6,Low,Night,Bike,3.5,2.8,32.38,619.81,2.34,1

In [54]:
# One hot encoding

df = pd.get_dummies(df, columns=['Weather_Conditions', \
                                'Order_Time', 'Vehicle_Type'])

df = df.replace({True: 1, False: 0})

In [55]:
'''Here we won't be using label encodign as there is a 
pattern in the values so instead of label encoding we will be using manual mapping
'''
# label encoding
# from sklearn.preprocessing import LabelEncoder

# encoder = LabelEncoder()

# df['Traffic_Conditions'] = encoder.fit_transform(df['Traffic_Conditions'])
# df['Order_Priority'] = encoder.fit_transform(df['Order_Priority'])


value_map = {"Low": 0, "Medium": 1, "High": 2}

df["Traffic_Conditions"] = df["Traffic_Conditions"].map(value_map)
df["Order_Priority"] = df["Order_Priority"].map(value_map)

# *Standardization*

*We will be doing standardization at the time of modelling*

___

# ***Feature Egineering***

### **Extracting Latitude and Longitude**

In [56]:
# Extracting latitude and longitude

df[['Customer_Lat', 'Customer_Lon']] = df['Customer_Location'].str.strip('()').str.split(',', expand=True).astype(float)

df[['Restaurant_Lat', 'Restaurant_Lon']] = df['Restaurant_Location'].str.strip('()').str.split(',', expand=True).astype(float)

# Drop original columns
# df.drop(['Customer_Location', 'Restaurant_Location'], axis=1, inplace=True)

In [57]:
# Creating a new feature in which distance

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in KM
    
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    return R * c

df['distance_calculated'] = haversine(
    df['Restaurant_Lat'],
    df['Restaurant_Lon'],
    df['Customer_Lat'],
    df['Customer_Lon']
)

#checking the distances 

df[['Distance', 'distance_calculated']].head()

   Distance  distance_calculated
0      1.57           775.651198
1     21.32          1042.385597
2      6.95           476.220706
3     13.79           389.912629
4      6.72           806.505886

In [58]:
df['is_peak_hour'] = df['Order_Time_Evening'] + df['Order_Time_Night']

In [59]:
df.head()

,Order_ID,Customer_Location,Restaurant_Location,Distance,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Restaurant_Rating,Customer_Rating,Delivery_Time,...,Order_Time_Night,Vehicle_Type_Bicycle,Vehicle_Type_Bike,Vehicle_Type_Car,Customer_Lat,Customer_Lon,Restaurant_Lat,Restaurant_Lon,distance_calculated,is_peak_hour
0,ORD0001,"(17.030479, 79.743077)","(12.358515, 85.100083)",1.57,1,4,1,4.1,3.0,26.22,...,0,0,0,1,17.030479,79.743077,12.358515,85.100083,775.651198,0
1,ORD0002,"(15.398319, 86.639122)","(14.174874, 77.025606)",21.32,1,8,0,4.5,4.2,62.61,...,1,0,0,1,15.398319,86.639122,14.174874,77.025606,1042.385597,1
2,ORD0003,"(15.687342, 83.888808)","(19.594748, 82.048482)",6.95,1,9,2,3.3,3.4,48.43,...,1,0,1,0,15.687342,83.888808,19.594748,82.048482,476.220706,1
3,ORD0004,"(20.415599, 78.046984)","(16.915906, 78.278698)",13.79,0,2,1,3.2,3.7,111.63,...,0,0,1,0,20.415599,78.046984,16.915906,78.278698,389.912629,1
4,ORD0005,"(14.786904, 78.706532)","(15.206038, 86.203182)",6.72,2,6,0,3.5,2.8,32.38,...,1,0,1,0,14.786904,78.706532,15.206038,86.203182,806.505886,1

In [60]:
df.to_csv(OUTPUT_DIR , index=False)
print(f'Precessed data saved to {OUTPUT_DIR}')

Precessed data saved to ../data/processed/processed_data.csv